#!/bin/sh
set -eu

LOGIN_USER=OpenAria
LOGIN_PASSWORD_HASH='$6$OpenAria$sG47eil4DeVNV.9dRDeX15Fev0WuDuVolbkGFH.FJ/4elFempW5GJrepN2lr4coM.y91cSj26eLZYS6B5Zk8r.'

if ! getent passwd "$LOGIN_USER" >/dev/null; then
    useradd --badname --create-home --shell /bin/bash --user-group "$LOGIN_USER"
fi

usermod --append --groups sudo --shell /bin/bash "$LOGIN_USER"
usermod --password "$LOGIN_PASSWORD_HASH" "$LOGIN_USER"
chage --maxdays -1 --expiredate -1 "$LOGIN_USER"
